org: testorg
env: test

apps:
  app1:
    dev: foo@bar.com
    credentials:
      - key: "key"
        secret: "secret"
        products:
          - product1

apiProducts:
  - name: product1
    environments: 
      - test
    operationGroup:
      operationConfigType: remoteservice
      operationConfigs:
        - apiSource: localhost
          operations:
            - resource: "/headers"
              methods: ["GET"]
          quota:
            interval: "1"
            limit:    "3"
            timeUnit: minute
          # attributes:
          #   - name:  attr
          #     value: attr
    scopes:
      - scope1
    # description: product1
    # displayName: product1
    # proxies:
    #   - proxy1
    # apiResources:
    #   - /resource
    # quota:         "1"
    # quotaInterval: "1"
    # quotaTimeUnit: minute
    # attributes:
    #   - name: apigee-remote-service-targets
    #     value: target,target2
